# Generated by Django 4.2.2 on 2023-06-27 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factory_order', models.CharField(max_length=8)),
                ('factory_order_date', models.DateField(default=datetime.datetime.now)),
                ('article_number', models.CharField(max_length=20)),
                ('datasheet', models.BooleanField()),
                ('datasheet_date', models.DateField(default=datetime.datetime.now)),
                ('etools', models.BooleanField()),
                ('sticker', models.BooleanField()),
                ('sticker_date', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Fields',
                'verbose_name_plural': 'Fields',
                'ordering': ['factory_order'],
            },
        ),
    ]
