# Generated by Django 4.2.2 on 2023-06-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlFO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fields',
            options={'ordering': ['factory_order'], 'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AddField(
            model_name='fields',
            name='ecl',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='factory_order',
            field=models.CharField(max_length=10),
        ),
    ]
