# Generated by Django 4.2.2 on 2023-06-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlFO', '0002_alter_fields_options_fields_ecl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='datasheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fields',
            name='etools',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fields',
            name='sticker',
            field=models.BooleanField(default=False),
        ),
    ]
